# Generated by Django 5.1.3 on 2024-12-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_rate', models.FloatField()),
                ('assignment_completion_rate', models.FloatField()),
                ('average_assignment_score', models.FloatField()),
                ('mid_term_grade', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
