# Generated by Django 5.1.3 on 2025-01-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('evaluations', '0002_initial'),
        ('users', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentresult',
            unique_together={('student', 'subject')},
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='semester',
        ),
    ]
