# Generated by Django 5.1.3 on 2024-12-30 06:01

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/default_profile.jpg', upload_to=users.models.rename_profile_picture, validators=[users.models.file_size]),
        ),
    ]
